backend:
  name: github
  repo: aldnlee/lifeatpih
  branch: main
  # URL di bawah ini harus sama dengan URL Worker kamu
  base_url: https://lifeatpih.denleerider354.workers.dev 
  auth_endpoint: /auth

# --- TAMBAHKAN INI ---
media_library:
  name: cloudinary
  config:
    cloud_name: "drfdkdkik"
    api_key: "754964683383539"
    upload_preset: ml_default

collections:
  - name: "teams"
    label: "PIH Teams"
    folder: "src/content/teams"
    create: true
    format: "json"
    fields:
      - { label: "Batch Name", name: "title", widget: "string" }
      - label: "Roles"
        name: "roles"
        widget: "list"
        fields:
          - { label: "Role Name", name: "role_name", widget: "string" }
          - label: "Photos"
            name: "photos"
            widget: "list"
            # allow_multiple memungkigitnkan kamu pilih banyak foto sekaligus
            field: 
              label: "Image"
              name: "url"
              widget: "image"
              allow_multiple: true

  - name: "internal_docs"
    label: "Dokumen Internal"
    folder: "src/pages/internal" # Mengarah ke folder rahasia tadi
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
