backend:
  name: github
  repo: aldnlee/lifeatpih
  branch: main
  # Jangan gunakan base_url jika menggunakan Netlify/Git Gateway

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "teams"
    label: "PIH Teams"
    folder: "src/content/teams"
    create: true
    format: "json"
    fields:
      - { label: "Batch Name", name: "title", widget: "string" }
      - label: "Roles"
        name: "roles"
        widget: "list"
        fields:
          - { label: "Role Name", name: "role_name", widget: "string" }
          - label: "Photos"
            name: "photos"
            widget: "list"
            # PROPERTI 'NAME' WAJIB ADA DI SINI
            field: { label: "Image", name: "url", widget: "image" }