backend:
  name: git-gateway
  repo: aldnlee/lifeatpih
  branch: main

# --- TAMBAHKAN INI ---
media_library:
  name: cloudinary
  config:
    cloud_name: "drfdkdkik"
    api_key: "754964683383539"

collections:
  - name: "teams"
    label: "PIH Teams"
    folder: "src/content/teams"
    create: true
    format: "json"
    fields:
      - { label: "Batch Name", name: "title", widget: "string" }
      - label: "Roles"
        name: "roles"
        widget: "list"
        fields:
          - { label: "Role Name", name: "role_name", widget: "string" }
          - label: "Photos"
            name: "photos"
            widget: "list"
            # allow_multiple memungkigitnkan kamu pilih banyak foto sekaligus
            field: 
              label: "Image"
              name: "url"
              widget: "image"
              allow_multiple: true