backend:
  name: github
  repo: aldnlee/lifeatpih
  branch: main
  # Hapus base_url agar menggunakan default Git Gateway

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "teams"
    label: "PIH Teams"
    folder: "src/content/teams"
    create: true
    format: "json"
    fields:
      - { label: "Batch Name", name: "title", widget: "string" }
      - label: "Roles"
        name: "roles"
        widget: "list"
        fields:
          - { label: "Role Name", name: "role_name", widget: "string" }
          - label: "Photos"
            name: "photos"
            widget: "list"
            # Langsung gunakan widget image sebagai item list agar hasilnya array string
            field: { label: "Image", widget: "image" }